
[2018-08-16 17:02:27] Traceback (most recent call last):
  File "c:\Users\kimchips\.vscode\extensions\ms-python.python-2018.7.1\pythonFiles\PythonTools\visualstudio_py_launcher.py", line 91, in <module>
    vspd.debug(filename, port_num, debug_id, debug_options, currentPid, run_as)
  File "c:\Users\kimchips\.vscode\extensions\ms-python.python-2018.7.1\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 2621, in debug
    exec_module(file, globals_obj)
  File "c:\Users\kimchips\.vscode\extensions\ms-python.python-2018.7.1\pythonFiles\PythonTools\visualstudio_py_util.py", line 127, in exec_module
    runpy.run_module(module, global_variables, run_name=global_variables.get('__name__'), alter_sys=True)
  File "C:\Users\kimchips\Anaconda3\envs\Rulr\lib\runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "C:\Users\kimchips\Anaconda3\envs\Rulr\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\kimchips\Anaconda3\envs\Rulr\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\kimchips\Dropbox (Kimchi and Chips)\Rulr 2.0\Rulr\rulr\__main__.py", line 63, in <module>
    web_security_disabled=True)
  File "cefpython_py36.pyx", line 672, in cefpython_py36.CreateBrowserSync
Exception: Invalid argument: web_security_disabled


[2018-08-16 17:02:56] Traceback (most recent call last):
  File "c:\Users\kimchips\.vscode\extensions\ms-python.python-2018.7.1\pythonFiles\PythonTools\visualstudio_py_launcher.py", line 91, in <module>
    vspd.debug(filename, port_num, debug_id, debug_options, currentPid, run_as)
  File "c:\Users\kimchips\.vscode\extensions\ms-python.python-2018.7.1\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 2621, in debug
    exec_module(file, globals_obj)
  File "c:\Users\kimchips\.vscode\extensions\ms-python.python-2018.7.1\pythonFiles\PythonTools\visualstudio_py_util.py", line 127, in exec_module
    runpy.run_module(module, global_variables, run_name=global_variables.get('__name__'), alter_sys=True)
  File "C:\Users\kimchips\Anaconda3\envs\Rulr\lib\runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "C:\Users\kimchips\Anaconda3\envs\Rulr\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\kimchips\Anaconda3\envs\Rulr\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\kimchips\Dropbox (Kimchi and Chips)\Rulr 2.0\Rulr\rulr\__main__.py", line 63, in <module>
    web_security_disabled=True)
  File "cefpython_py36.pyx", line 672, in cefpython_py36.CreateBrowserSync
Exception: Invalid argument: web_security_disabled


[2018-08-16 18:54:17] Traceback (most recent call last):
  File "c:\Users\kimchips\.vscode\extensions\ms-python.python-2018.7.1\pythonFiles\PythonTools\visualstudio_py_launcher.py", line 91, in <module>
    vspd.debug(filename, port_num, debug_id, debug_options, currentPid, run_as)
  File "c:\Users\kimchips\.vscode\extensions\ms-python.python-2018.7.1\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 2629, in debug
    del THREADS[cur_thread.id]
KeyError: 18132


[2018-08-16 19:01:23] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py36.V8FunctionHandler_Execute
TypeError: getNodeByPath() takes 2 positional arguments but 3 were given


[2018-08-16 19:32:18] Traceback (most recent call last):
  File "c:\Users\kimchips\.vscode\extensions\ms-python.python-2018.7.1\pythonFiles\PythonTools\visualstudio_py_launcher.py", line 91, in <module>
    vspd.debug(filename, port_num, debug_id, debug_options, currentPid, run_as)
  File "c:\Users\kimchips\.vscode\extensions\ms-python.python-2018.7.1\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 2629, in debug
    del THREADS[cur_thread.id]
KeyError: 20316


[2018-08-16 21:48:51] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py36.V8FunctionHandler_Execute
  File "C:\Users\kimchips\Dropbox (Kimchi and Chips)\Rulr 2.0\Rulr\rulr\Utils\_Exports.py", line 72, in call_exported_object
    raise Exception("object_id {0} not found in exported_objects".format(object_id))
Exception: object_id None not found in exported_objects


[2018-08-16 21:57:17] Traceback (most recent call last):
  File "c:\Users\kimchips\.vscode\extensions\ms-python.python-2018.7.1\pythonFiles\PythonTools\visualstudio_py_launcher.py", line 91, in <module>
    vspd.debug(filename, port_num, debug_id, debug_options, currentPid, run_as)
  File "c:\Users\kimchips\.vscode\extensions\ms-python.python-2018.7.1\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 2629, in debug
    del THREADS[cur_thread.id]
KeyError: 15872


[2018-08-16 22:07:36] Traceback (most recent call last):
  File "c:\Users\kimchips\.vscode\extensions\ms-python.python-2018.7.1\pythonFiles\PythonTools\visualstudio_py_launcher.py", line 91, in <module>
    vspd.debug(filename, port_num, debug_id, debug_options, currentPid, run_as)
  File "c:\Users\kimchips\.vscode\extensions\ms-python.python-2018.7.1\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 2629, in debug
    del THREADS[cur_thread.id]
KeyError: 5028


[2018-08-17 13:09:12] Traceback (most recent call last):
  File "c:\Users\kimchips\.vscode\extensions\ms-python.python-2018.7.1\pythonFiles\PythonTools\visualstudio_py_launcher.py", line 91, in <module>
    vspd.debug(filename, port_num, debug_id, debug_options, currentPid, run_as)
  File "c:\Users\kimchips\.vscode\extensions\ms-python.python-2018.7.1\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 2629, in debug
    del THREADS[cur_thread.id]
KeyError: 19616


[2018-08-17 17:41:03] Traceback (most recent call last):
  File "c:\Users\kimchips\.vscode\extensions\ms-python.python-2018.7.1\pythonFiles\PythonTools\visualstudio_py_launcher.py", line 91, in <module>
    vspd.debug(filename, port_num, debug_id, debug_options, currentPid, run_as)
  File "c:\Users\kimchips\.vscode\extensions\ms-python.python-2018.7.1\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 2621, in debug
    exec_module(file, globals_obj)
  File "c:\Users\kimchips\.vscode\extensions\ms-python.python-2018.7.1\pythonFiles\PythonTools\visualstudio_py_util.py", line 127, in exec_module
    runpy.run_module(module, global_variables, run_name=global_variables.get('__name__'), alter_sys=True)
  File "C:\Users\kimchips\Anaconda3\envs\Rulr\lib\runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "C:\Users\kimchips\Anaconda3\envs\Rulr\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\kimchips\Anaconda3\envs\Rulr\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\kimchips\Dropbox (Kimchi and Chips)\Rulr 2.0\Rulr\rulr\__main__.py", line 71, in <module>
    "v8-cache-option" : "off"
  File "cefpython_py36.pyx", line 627, in cefpython_py36.Initialize
  File "settings.pyx", line 133, in cefpython_py36.SetApplicationSettings
Exception: Invalid appSettings key: v8-cache-option


[2018-08-17 17:41:26] Traceback (most recent call last):
  File "c:\Users\kimchips\.vscode\extensions\ms-python.python-2018.7.1\pythonFiles\PythonTools\visualstudio_py_launcher.py", line 91, in <module>
    vspd.debug(filename, port_num, debug_id, debug_options, currentPid, run_as)
  File "c:\Users\kimchips\.vscode\extensions\ms-python.python-2018.7.1\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 2621, in debug
    exec_module(file, globals_obj)
  File "c:\Users\kimchips\.vscode\extensions\ms-python.python-2018.7.1\pythonFiles\PythonTools\visualstudio_py_util.py", line 127, in exec_module
    runpy.run_module(module, global_variables, run_name=global_variables.get('__name__'), alter_sys=True)
  File "C:\Users\kimchips\Anaconda3\envs\Rulr\lib\runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "C:\Users\kimchips\Anaconda3\envs\Rulr\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\kimchips\Anaconda3\envs\Rulr\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\kimchips\Dropbox (Kimchi and Chips)\Rulr 2.0\Rulr\rulr\__main__.py", line 71, in <module>
    "v8-cache-option" : "off"
  File "cefpython_py36.pyx", line 627, in cefpython_py36.Initialize
  File "settings.pyx", line 133, in cefpython_py36.SetApplicationSettings
Exception: Invalid appSettings key: v8-cache-option

